# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

- message:
  - name: Weeds exported
  - module: [HSE.Util, GHC.Util.FreeVars, GHC.Util.HsExpr, GHC.Util.View, GHC.Util.W, Hint.Type, Idea,GHC.Util.Brackets,GHC.Util.Language.Haskell.GHC.ExactPrint.Types,GHC.Util.Refact.Utils, GHC.Util.Unify, GHC.Util.Scope,Hint.Match]

- message:
  - name: Redundant build-depends entry
  - depends: [ghc-lib, ghc, ghc-boot-th] # Only some subset is supported
