# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

- message:
  - name: Weeds exported
  - module: [HSE.Util, GHC.Util.FreeVars, GHC.Util.HsExpr, GHC.Util.View, GHC.Util.W, Hint.Type, Idea]
