# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

- message:
  - name: Redundant build-depends entry
  - depends: [ghc-lib-parser, ghc, ghc-boot-th, ghc-boot] # Only some subset is required
