resolver: lts-13.21 # ghc-8.6.5

ghc-options:
  # try and speed up recompilation on the CI server
  "$everything": -O0 -j

packages:
- .

extra-deps:
  - haskell-src-exts-1.21.0
  - haskell-src-exts-util-0.2.5
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-8.8.0.20190730.tar.gz
