resolver: lts-13.21 # ghc-8.6.5
packages: [.]
extra-deps:
  - haskell-src-exts-1.21.0
  - haskell-src-exts-util-0.2.5
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-8.8.1.20191204.tar.gz
  - github: shayne-fletcher/ghc-lib-parser-ex
    commit: "5fe76338cb231d28b5f50d9dfbd10c9eb49b5b08"
    sha256: "6d6ddc0b62c51a697812d8ebcd8d1aaeaaa875b0d91bce5972a5b364e83c2e9d"
ghc-options:
    "$locals": -Wunused-imports -Worphans -Wunused-top-binds -Wunused-local-binds -Wincomplete-patterns
flags:
  hlint:
    ghc-lib: true
