resolver: lts-14.27 # ghc-8.6.5
packages: [.]
extra-deps:
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-8.8.1.20200225.tar.gz
  - ghc-lib-parser-ex-8.8.5.8
  - extra-1.7.1
ghc-options:
    "$locals": -Wunused-imports -Worphans -Wunused-top-binds -Wunused-local-binds -Wincomplete-patterns
flags:
  hlint:
    ghc-lib: true
  ghc-lib-parser-ex:
    ghc-lib:  true
