resolver: lts-13.21 # ghc-8.6.5
packages: [.]
extra-deps:
  - haskell-src-exts-1.21.0
  - haskell-src-exts-util-0.2.5
  - archive: https://digitalassetsdk.bintray.com/ghc-lib/ghc-lib-parser-8.8.1.20200122.tar.gz
  - ghc-lib-parser-ex-8.8.3.0
ghc-options:
    "$locals": -Wunused-imports -Worphans -Wunused-top-binds -Wunused-local-binds -Wincomplete-patterns
flags:
  hlint:
    ghc-lib: true
  ghc-lib-parser-ex:
    ghc-lib:  true
